# Makefile: build docker image
# make mnb

PKGNAME := tonyzhang/phyapps-notebook:dev

pack:
	tar cjvf phycloud.tar.bz2 app templates static \
		config.py requirements.txt run.py

build: pack
	docker build --no-cache -t $(PKGNAME) .

push: build
	docker tag $(PKGNAME) $(PKGNAME)
	docker push $(PKGNAME)

