"""empty message

Revision ID: e7b785ac2804
Revises: 74297a19122a
Create Date: 2017-11-08 16:37:20.368521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b785ac2804'
down_revision = '74297a19122a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'timestamp')
    # ### end Alembic commands ###
