version: '3.7'

services:

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: E=mc^2
      MYSQL_DATABASE: phyapps_cloud
      MYSQL_USER: phyapps_admin
      MYSQL_PASSWORD: fa309026
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure

  chp:
    image: "jupyterhub/configurable-http-proxy"
    environment:
      - CONFIGPROXY_AUTH_TOKEN=${TOKEN}
    volumes:
      - ${PWD}/ssl:/ssl
    command: --default-target http://127.0.0.1:5050 --ip ${SRV_IP} --port 8000 --ssl-cert /ssl/cert.pem --ssl-key /ssl/key.pem --log-level debug
    networks:
      hostnet: {}
    deploy:
      restart_policy:
        condition: on-failure

  gateway:
    image: "tonyzhang/phyapps-gateway:latest"
    environment:
      - DB_NAME=phyapps_cloud
      - DB_USER=phyapps_admin
      - DB_PASS=fa309026
      - PROXY_TOKEN=${TOKEN}
      - PROXY_BASE=http://127.0.0.1:8001/api/routes
      - DPATH=${PWD}/data
    networks:
      hostnet: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db-data:
  portainer_data:

networks:
  hostnet:
    external: true
    name: host
